ALTER TABLE daily_logs ADD COLUMN IF NOT EXISTS total_fibers        DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE daily_logs ADD COLUMN IF NOT EXISTS total_sugars        DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE daily_logs ADD COLUMN IF NOT EXISTS total_saturated_fat DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE daily_logs ADD COLUMN IF NOT EXISTS total_salt          DOUBLE PRECISION NOT NULL DEFAULT 0;
